sudo: required

env:
  global:
    - container_id: $(mktemp)
    - role: /etc/ansible/roles/role_under_test
    - test_playbook: ${role}/tests/test.yml

  matrix:
    - distribution: centos
      version: 7
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  - git fetch origin tests
  - git worktree add tests origin/tests
  # Pull container
  - sudo docker pull bertvv/ansible-testing:${distribution}_${version}

script:
    # Run container in detached state
  - >
    sudo docker run --detach --volume="${PWD}:${role}:ro" ${run_opts}
    bertvv/ansible-testing:${distribution}_${version} "${init}" > "${container_id}"

  # Ansible syntax check.
  - >
    sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook ${test_playbook} --syntax-check

  # Test role.
  - >
    sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook ${test_playbook}

  # Test role idempotence.
  - >
    sudo docker exec "$(cat ${container_id})" ansible-playbook ${test_playbook}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'
